homepage: "https://simdutf.github.io/simdutf"
language: c++
primary_contact: "lemire@gmail.com"
main_repo: "https://github.com/simdutf/simdutf"
auto_ccs:
  - "nathaniel.brough@gmail.com"
  - "pauldreikossfuzz@gmail.com"

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer
